version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_USER: pyro
      POSTGRES_PASSWORD: pyroadmin
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    restart: always


  adminer:
    image: adminer
    container_name: pgadmin-container
    restart: always
    ports:
      - 8080:8080
    volumes:
      - pg-adminer:/var/lib/pg-adminer

volumes:
  pgvector-data:
  pg-adminer:
